function []=FDsolverSettings(MWS)
FDSOLVER = invoke(MWS, 'FDSolver');
invoke(FDSOLVER, 'Reset');
invoke(FDSOLVER, 'SetMethod', 'Tetrahedral', 'General purpose');
invoke(FDSOLVER, 'OrderTet', 'Second');
invoke(FDSOLVER, 'OrderSrf', 'First');
invoke(FDSOLVER, 'Stimulation', 'List', 'List');
invoke(FDSOLVER, 'ResetExcitationList');
invoke(FDSOLVER, 'AddToExcitationList', 'Zmax', 'TE(0,0);TM(0,0)');
invoke(FDSOLVER, 'AutoNormImpedance', 'False');
invoke(FDSOLVER, 'NormingImpedance', '50');
invoke(FDSOLVER, 'ModesOnly', 'False');
invoke(FDSOLVER, 'ConsiderPortLossesTet', 'True');
invoke(FDSOLVER, 'SetShieldAllPorts', 'False');
invoke(FDSOLVER, 'AccuracyHex', '1e-6');
invoke(FDSOLVER, 'AccuracyTet', '1e-4');
invoke(FDSOLVER, 'AccuracySrf', '1e-3');
invoke(FDSOLVER, 'LimitIterations', 'False');
invoke(FDSOLVER, 'MaxIterations', '0');
invoke(FDSOLVER, 'SetCalcBlockExcitationsInParallel', 'True', 'True', '');
invoke(FDSOLVER, 'StoreAllResults', 'False');
invoke(FDSOLVER, 'StoreResultsInCache', 'False');
invoke(FDSOLVER, 'UseHelmholtzEquation', 'True');
invoke(FDSOLVER, 'LowFrequencyStabilization', 'False');
invoke(FDSOLVER, 'Type', 'Auto');
invoke(FDSOLVER, 'MeshAdaptionHex', 'False');
invoke(FDSOLVER, 'MeshAdaptionTet', 'True');
invoke(FDSOLVER, 'AcceleratedRestart', 'True');
invoke(FDSOLVER, 'FreqDistAdaptMode', 'Distributed');
invoke(FDSOLVER, 'NewIterativeSolver', 'True');
invoke(FDSOLVER, 'TDCompatibleMaterials', 'False');
invoke(FDSOLVER, 'ExtrudeOpenBC', 'False');
invoke(FDSOLVER, 'SetOpenBCTypeHex', 'Default');
invoke(FDSOLVER, 'SetOpenBCTypeTet', 'Default');
invoke(FDSOLVER, 'AddMonitorSamples', 'True');
invoke(FDSOLVER, 'CalcStatBField', 'False');
invoke(FDSOLVER, 'CalcPowerLoss', 'True');
invoke(FDSOLVER, 'CalcPowerLossPerComponent', 'False');
invoke(FDSOLVER, 'StoreSolutionCoefficients', 'True');
invoke(FDSOLVER, 'UseDoublePrecision', 'False');
invoke(FDSOLVER, 'UseDoublePrecision_ML', 'True');
invoke(FDSOLVER, 'MixedOrderSrf', 'False');
invoke(FDSOLVER, 'MixedOrderTet', 'False');
invoke(FDSOLVER, 'PreconditionerAccuracyIntEq', '0.15');
invoke(FDSOLVER, 'MLFMMAccuracy', 'Default');
invoke(FDSOLVER, 'MinMLFMMBoxSize', '0.3');
invoke(FDSOLVER, 'UseCFIEForCPECIntEq', 'True');
invoke(FDSOLVER, 'UseFastRCSSweepIntEq', 'false');
invoke(FDSOLVER, 'UseSensitivityAnalysis', 'False');
invoke(FDSOLVER, 'RemoveAllStopCriteria', 'Hex');
invoke(FDSOLVER, 'AddStopCriterion', 'All S-Parameters', '0.01', '2', 'Hex', 'True');
invoke(FDSOLVER, 'AddStopCriterion', 'Reflection S-Parameters', '0.01', '2', 'Hex', 'False');
invoke(FDSOLVER, 'AddStopCriterion', 'Transmission S-Parameters', '0.01', '2', 'Hex', 'False');
invoke(FDSOLVER, 'RemoveAllStopCriteria', 'Tet');
invoke(FDSOLVER, 'AddStopCriterion', 'All S-Parameters', '0.01', '2', 'Tet', 'True');
invoke(FDSOLVER, 'AddStopCriterion', 'Reflection S-Parameters', '0.01', '2', 'Tet', 'False');
invoke(FDSOLVER, 'AddStopCriterion', 'Transmission S-Paramieters', '0.01', '2', 'Tet', 'False');
invoke(FDSOLVER, 'AddStopCriterion', 'All Probes', '0.05', '2', 'Tet', 'True');
invoke(FDSOLVER, 'RemoveAllStopCriteria', 'Srf');
invoke(FDSOLVER, 'AddStopCriterion', 'All S-Parameters', '0.01', '2', 'Srf', 'True');
invoke(FDSOLVER, 'AddStopCriterion', 'Reflection S-Parameters', '0.01', '2', 'Srf', 'False');
invoke(FDSOLVER, 'AddStopCriterion', 'Transmission S-Parameters', '0.01', '2', 'Srf', 'False');
invoke(FDSOLVER, 'SweepMinimumSamples', '3');
invoke(FDSOLVER, 'SetNumberOfResultDataSamples', '1001');
invoke(FDSOLVER, 'SetResultDataSamplingMode', 'Automatic');
invoke(FDSOLVER, 'SweepWeightEvanescent', '1.0');
invoke(FDSOLVER, 'AccuracyROM', '1e-4');
% invoke(FDSOLVER, 'AddSampleInterval', '', '', '1', 'Automatic', 'True');
% invoke(FDSOLVER, 'AddSampleInterval', '', '', '', 'Automatic', 'False');
invoke(FDSOLVER, 'MPIParallelization', 'False');
invoke(FDSOLVER, 'UseDistributedComputing', 'False');
invoke(FDSOLVER, 'NetworkComputingStrategy', 'RunRemote');
invoke(FDSOLVER, 'NetworkComputingJobCount', '3');
invoke(FDSOLVER, 'UseParallelization', 'True');
invoke(FDSOLVER, 'MaxCPUs', '96');
invoke(FDSOLVER, 'MaximumNumberOfCPUDevices', '2');
release(FDSOLVER);
end